apiVersion: v1
kind: ConfigMap
metadata:
  name: arrosage-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://arrosage-db:3306/arrosage_db"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arrosage-service
  labels:
    app: arrosage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arrosage-service
  template:
    metadata:
      labels:
        app: arrosage-service
    spec:
      containers:
      - name: arrosage-service
        image: irrigation/arrosage-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: arrosage-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: arrosage-config
              key: SPRING_RABBITMQ_HOST
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: arrosage-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: arrosage-service
spec:
  selector:
    app: arrosage-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arrosage-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arrosage-db
  template:
    metadata:
      labels:
        app: arrosage-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "arrosage_db"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        volumeMounts:
        - name: arrosage-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: arrosage-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: arrosage-db
spec:
  selector:
    app: arrosage-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
